=begin
#Dependency-Track API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for DependencyTacker::AnalysisApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AnalysisApi' do
  before do
    # run before each test
    @api_instance = DependencyTacker::AnalysisApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnalysisApi' do
    it 'should create an instance of AnalysisApi' do
      expect(@api_instance).to be_instance_of(DependencyTacker::AnalysisApi)
    end
  end

  # unit tests for retrieve_analysis
  # Retrieves an analysis trail
  # @param component The UUID of the component
  # @param vulnerability The UUID of the vulnerability
  # @param [Hash] opts the optional parameters
  # @option opts [String] :project The UUID of the project
  # @return [Analysis]
  describe 'retrieve_analysis test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_analysis
  # Records an analysis decision
  # @param [Hash] opts the optional parameters
  # @option opts [AnalysisRequest] :body 
  # @return [Analysis]
  describe 'update_analysis test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_global_analysis
  # Records an analysis decision
  # @param [Hash] opts the optional parameters
  # @option opts [AnalysisRequest] :body 
  # @return [Analysis]
  describe 'update_global_analysis test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
