=begin
#Dependency-Track API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for DependencyTacker::CalculatorApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CalculatorApi' do
  before do
    # run before each test
    @api_instance = DependencyTacker::CalculatorApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CalculatorApi' do
    it 'should create an instance of CalculatorApi' do
      expect(@api_instance).to be_instance_of(DependencyTacker::CalculatorApi)
    end
  end

  # unit tests for get_cvss_scores
  # Returns the CVSS base score, impact sub-score and exploitability sub-score
  # @param vector A valid CVSSv2 or CVSSv3 vector
  # @param [Hash] opts the optional parameters
  # @return [Score]
  describe 'get_cvss_scores test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
