=begin
#Dependency-Track API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for DependencyTacker::CweApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CweApi' do
  before do
    # run before each test
    @api_instance = DependencyTacker::CweApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CweApi' do
    it 'should create an instance of CweApi' do
      expect(@api_instance).to be_instance_of(DependencyTacker::CweApi)
    end
  end

  # unit tests for get_cwe
  # Returns a specific CWE
  # @param cwe_id The CWE ID of the CWE to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Cwe]
  describe 'get_cwe test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_cwes
  # Returns a list of all CWEs
  # @param [Hash] opts the optional parameters
  # @return [Array<Cwe>]
  describe 'get_cwes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
