=begin
#Dependency-Track API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for DependencyTacker::FindingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FindingApi' do
  before do
    # run before each test
    @api_instance = DependencyTacker::FindingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FindingApi' do
    it 'should create an instance of FindingApi' do
      expect(@api_instance).to be_instance_of(DependencyTacker::FindingApi)
    end
  end

  # unit tests for export_findings_by_project
  # Returns a the findings for the specified project as FPF
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'export_findings_by_project test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_findings_by_project
  # Returns a list of all findings for a specific project
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [Array<Finding>]
  describe 'get_findings_by_project test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
