=begin
#Dependency-Track API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for DependencyTacker::LdapApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LdapApi' do
  before do
    # run before each test
    @api_instance = DependencyTacker::LdapApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LdapApi' do
    it 'should create an instance of LdapApi' do
      expect(@api_instance).to be_instance_of(DependencyTacker::LdapApi)
    end
  end

  # unit tests for add_mapping
  # Adds a mapping
  # @param [Hash] opts the optional parameters
  # @option opts [MappedLdapGroupRequest] :body 
  # @return [MappedLdapGroup]
  describe 'add_mapping test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_mapping
  # Removes a mapping
  # @param uuid The UUID of the mapping to delete
  # @param [Hash] opts the optional parameters
  # @return [MappedLdapGroup]
  describe 'delete_mapping test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retrieve_ldap_groups
  # Returns the DNs of all accessible groups within the directory
  # This API performs a pass-thru query to the configured LDAP server. Search criteria results are cached using default Alpine CacheManager policy
  # @param [Hash] opts the optional parameters
  # @return [Array<String>]
  describe 'retrieve_ldap_groups test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retrieve_ldap_groups1
  # Returns the DNs of all groups mapped to the specified team
  # @param uuid The UUID of the team to retrieve mappings for
  # @param [Hash] opts the optional parameters
  # @return [Array<String>]
  describe 'retrieve_ldap_groups1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
