=begin
#Dependency-Track API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for DependencyTacker::MetricsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MetricsApi' do
  before do
    # run before each test
    @api_instance = DependencyTacker::MetricsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MetricsApi' do
    it 'should create an instance of MetricsApi' do
      expect(@api_instance).to be_instance_of(DependencyTacker::MetricsApi)
    end
  end

  # unit tests for get_component_current_metrics
  # Returns current metrics for a specific component
  # @param uuid The UUID of the component to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [ComponentMetrics]
  describe 'get_component_current_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_component_metrics_since
  # Returns historical metrics for a specific component from a specific date
  # Date format must be YYYYMMDD
  # @param uuid The UUID of the component to retrieve metrics for
  # @param date The start date to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [Array<ComponentMetrics>]
  describe 'get_component_metrics_since test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_component_metrics_x_days
  # Returns X days of historical metrics for a specific component
  # @param uuid The UUID of the component to retrieve metrics for
  # @param days The number of days back to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [Array<ComponentMetrics>]
  describe 'get_component_metrics_x_days test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_dependency_current_metrics
  # Returns current metrics for a specific dependency
  # @param project_uuid The UUID of the project to retrieve metrics for
  # @param component_uuid The UUID of the component to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [DependencyMetrics]
  describe 'get_dependency_current_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_dependency_metrics_since
  # Returns historical metrics for a specific dependency from a specific date
  # Date format must be YYYYMMDD
  # @param project_uuid The UUID of the project to retrieve metrics for
  # @param component_uuid The UUID of the component to retrieve metrics for
  # @param date The start date to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [Array<DependencyMetrics>]
  describe 'get_dependency_metrics_since test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_dependency_metrics_x_days
  # Returns X days of historical metrics for a specific dependency
  # @param project_uuid The UUID of the project to retrieve metrics for
  # @param component_uuid The UUID of the component to retrieve metrics for
  # @param days The number of days back to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [Array<DependencyMetrics>]
  describe 'get_dependency_metrics_x_days test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_portfolio_current_metrics
  # Returns current metrics for the entire portfolio
  # @param [Hash] opts the optional parameters
  # @return [PortfolioMetrics]
  describe 'get_portfolio_current_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_portfolio_metrics_since
  # Returns historical metrics for the entire portfolio from a specific date
  # Date format must be YYYYMMDD
  # @param date The start date to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [Array<PortfolioMetrics>]
  describe 'get_portfolio_metrics_since test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_portfolio_metrics_x_days
  # Returns X days of historical metrics for the entire portfolio
  # @param days The number of days back to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [Array<PortfolioMetrics>]
  describe 'get_portfolio_metrics_x_days test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_current_metrics
  # Returns current metrics for a specific project
  # @param uuid The UUID of the project to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [ProjectMetrics]
  describe 'get_project_current_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_metrics_since
  # Returns historical metrics for a specific project from a specific date
  # Date format must be YYYYMMDD
  # @param uuid The UUID of the project to retrieve metrics for
  # @param date The start date to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [Array<ProjectMetrics>]
  describe 'get_project_metrics_since test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_metrics_x_days
  # Returns X days of historical metrics for a specific project
  # @param uuid The UUID of the project to retrieve metrics for
  # @param days The number of days back to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [Array<ProjectMetrics>]
  describe 'get_project_metrics_x_days test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_vulnerability_metrics
  # Returns the sum of all vulnerabilities in the database by year and month
  # @param [Hash] opts the optional parameters
  # @return [Array<VulnerabilityMetrics>]
  describe 'get_vulnerability_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for refresh_component_metrics
  # Requests a refresh of a specific components metrics
  # @param uuid The UUID of the component to refresh metrics on
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'refresh_component_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for refresh_dependency_metrics
  # Requests a refresh of a specific dependency metrics
  # @param project_uuid The UUID of the project to retrieve metrics for
  # @param component_uuid The UUID of the component to retrieve metrics for
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'refresh_dependency_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for refresh_portfolio_metrics
  # Requests a refresh of the portfolio metrics
  # @param [Hash] opts the optional parameters
  # @return [PortfolioMetrics]
  describe 'refresh_portfolio_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for refresh_project_metrics
  # Requests a refresh of a specific projects metrics
  # @param uuid The UUID of the project to refresh metrics on
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'refresh_project_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
