=begin
#Dependency-Track API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for DependencyTacker::ProjectPropertyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProjectPropertyApi' do
  before do
    # run before each test
    @api_instance = DependencyTacker::ProjectPropertyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectPropertyApi' do
    it 'should create an instance of ProjectPropertyApi' do
      expect(@api_instance).to be_instance_of(DependencyTacker::ProjectPropertyApi)
    end
  end

  # unit tests for create_property
  # Creates a new project property
  # @param uuid The UUID of the project to create a property for
  # @param [Hash] opts the optional parameters
  # @option opts [ProjectProperty] :body 
  # @return [ProjectProperty]
  describe 'create_property test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_property
  # Deletes a config property
  # @param uuid The UUID of the project to delete a property from
  # @param [Hash] opts the optional parameters
  # @option opts [ProjectProperty] :body 
  # @return [ProjectProperty]
  describe 'delete_property test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_properties
  # Returns a list of all ProjectProperties for the specified project
  # @param uuid The UUID of the project to retrieve properties for
  # @param [Hash] opts the optional parameters
  # @return [Array<ProjectProperty>]
  describe 'get_properties test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_property
  # Updates a project property
  # @param uuid The UUID of the project to create a property for
  # @param [Hash] opts the optional parameters
  # @option opts [ProjectProperty] :body 
  # @return [ProjectProperty]
  describe 'update_property test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
