=begin
#Dependency-Track API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for DependencyTacker::SearchApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SearchApi' do
  before do
    # run before each test
    @api_instance = DependencyTacker::SearchApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SearchApi' do
    it 'should create an instance of SearchApi' do
      expect(@api_instance).to be_instance_of(DependencyTacker::SearchApi)
    end
  end

  # unit tests for search
  # Processes and returns search results
  # Use of this endpoint may lead to URL encoding/decoding issues and is not recommended
  # @param query 
  # @param [Hash] opts the optional parameters
  # @return [SearchResult]
  describe 'search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search_via_query_string
  # Processes and returns search results
  # Preferred search endpoint
  # @param [Hash] opts the optional parameters
  # @option opts [String] :query 
  # @return [SearchResult]
  describe 'search_via_query_string test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
