=begin
#Dependency-Track API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module DependencyTracker
  class ManagedUser
    attr_accessor :username

    attr_accessor :new_password

    attr_accessor :confirm_password

    attr_accessor :last_password_change

    attr_accessor :fullname

    attr_accessor :email

    attr_accessor :suspended

    attr_accessor :force_password_change

    attr_accessor :non_expiry_password

    attr_accessor :teams

    attr_accessor :permissions

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'username' => :'username',
        :'new_password' => :'newPassword',
        :'confirm_password' => :'confirmPassword',
        :'last_password_change' => :'lastPasswordChange',
        :'fullname' => :'fullname',
        :'email' => :'email',
        :'suspended' => :'suspended',
        :'force_password_change' => :'forcePasswordChange',
        :'non_expiry_password' => :'nonExpiryPassword',
        :'teams' => :'teams',
        :'permissions' => :'permissions'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'username' => :'String',
        :'new_password' => :'String',
        :'confirm_password' => :'String',
        :'last_password_change' => :'Integer',
        :'fullname' => :'String',
        :'email' => :'String',
        :'suspended' => :'Boolean',
        :'force_password_change' => :'Boolean',
        :'non_expiry_password' => :'Boolean',
        :'teams' => :'Array<Team>',
        :'permissions' => :'Array<Permission>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DependencyTracker::ManagedUser` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DependencyTracker::ManagedUser`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      end

      if attributes.key?(:'new_password')
        self.new_password = attributes[:'new_password']
      end

      if attributes.key?(:'confirm_password')
        self.confirm_password = attributes[:'confirm_password']
      end

      if attributes.key?(:'last_password_change')
        self.last_password_change = attributes[:'last_password_change']
      end

      if attributes.key?(:'fullname')
        self.fullname = attributes[:'fullname']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'suspended')
        self.suspended = attributes[:'suspended']
      end

      if attributes.key?(:'force_password_change')
        self.force_password_change = attributes[:'force_password_change']
      end

      if attributes.key?(:'non_expiry_password')
        self.non_expiry_password = attributes[:'non_expiry_password']
      end

      if attributes.key?(:'teams')
        if (value = attributes[:'teams']).is_a?(Array)
          self.teams = value
        end
      end

      if attributes.key?(:'permissions')
        if (value = attributes[:'permissions']).is_a?(Array)
          self.permissions = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@username.nil? && @username.to_s.length > 255
        invalid_properties.push('invalid value for "username", the character length must be smaller than or equal to 255.')
      end

      if !@username.nil? && @username.to_s.length < 1
        invalid_properties.push('invalid value for "username", the character length must be great than or equal to 1.')
      end

      pattern = Regexp.new(/[\P{Cc}]+/)
      if !@username.nil? && @username !~ pattern
        invalid_properties.push("invalid value for \"username\", must conform to the pattern #{pattern}.")
      end

      if !@new_password.nil? && @new_password.to_s.length > 255
        invalid_properties.push('invalid value for "new_password", the character length must be smaller than or equal to 255.')
      end

      if !@new_password.nil? && @new_password.to_s.length < 0
        invalid_properties.push('invalid value for "new_password", the character length must be great than or equal to 0.')
      end

      pattern = Regexp.new(/[\P{Cc}]+/)
      if !@new_password.nil? && @new_password !~ pattern
        invalid_properties.push("invalid value for \"new_password\", must conform to the pattern #{pattern}.")
      end

      if !@confirm_password.nil? && @confirm_password.to_s.length > 255
        invalid_properties.push('invalid value for "confirm_password", the character length must be smaller than or equal to 255.')
      end

      if !@confirm_password.nil? && @confirm_password.to_s.length < 0
        invalid_properties.push('invalid value for "confirm_password", the character length must be great than or equal to 0.')
      end

      pattern = Regexp.new(/[\P{Cc}]+/)
      if !@confirm_password.nil? && @confirm_password !~ pattern
        invalid_properties.push("invalid value for \"confirm_password\", must conform to the pattern #{pattern}.")
      end

      if @last_password_change.nil?
        invalid_properties.push('invalid value for "last_password_change", last_password_change cannot be nil.')
      end

      if !@fullname.nil? && @fullname.to_s.length > 255
        invalid_properties.push('invalid value for "fullname", the character length must be smaller than or equal to 255.')
      end

      if !@fullname.nil? && @fullname.to_s.length < 0
        invalid_properties.push('invalid value for "fullname", the character length must be great than or equal to 0.')
      end

      pattern = Regexp.new(/[\P{Cc}]+/)
      if !@fullname.nil? && @fullname !~ pattern
        invalid_properties.push("invalid value for \"fullname\", must conform to the pattern #{pattern}.")
      end

      if !@email.nil? && @email.to_s.length > 255
        invalid_properties.push('invalid value for "email", the character length must be smaller than or equal to 255.')
      end

      if !@email.nil? && @email.to_s.length < 0
        invalid_properties.push('invalid value for "email", the character length must be great than or equal to 0.')
      end

      pattern = Regexp.new(/[\P{Cc}]+/)
      if !@email.nil? && @email !~ pattern
        invalid_properties.push("invalid value for \"email\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@username.nil? && @username.to_s.length > 255
      return false if !@username.nil? && @username.to_s.length < 1
      return false if !@username.nil? && @username !~ Regexp.new(/[\P{Cc}]+/)
      return false if !@new_password.nil? && @new_password.to_s.length > 255
      return false if !@new_password.nil? && @new_password.to_s.length < 0
      return false if !@new_password.nil? && @new_password !~ Regexp.new(/[\P{Cc}]+/)
      return false if !@confirm_password.nil? && @confirm_password.to_s.length > 255
      return false if !@confirm_password.nil? && @confirm_password.to_s.length < 0
      return false if !@confirm_password.nil? && @confirm_password !~ Regexp.new(/[\P{Cc}]+/)
      return false if @last_password_change.nil?
      return false if !@fullname.nil? && @fullname.to_s.length > 255
      return false if !@fullname.nil? && @fullname.to_s.length < 0
      return false if !@fullname.nil? && @fullname !~ Regexp.new(/[\P{Cc}]+/)
      return false if !@email.nil? && @email.to_s.length > 255
      return false if !@email.nil? && @email.to_s.length < 0
      return false if !@email.nil? && @email !~ Regexp.new(/[\P{Cc}]+/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] username Value to be assigned
    def username=(username)
      if !username.nil? && username.to_s.length > 255
        fail ArgumentError, 'invalid value for "username", the character length must be smaller than or equal to 255.'
      end

      if !username.nil? && username.to_s.length < 1
        fail ArgumentError, 'invalid value for "username", the character length must be great than or equal to 1.'
      end

      pattern = Regexp.new(/[\P{Cc}]+/)
      if !username.nil? && username !~ pattern
        fail ArgumentError, "invalid value for \"username\", must conform to the pattern #{pattern}."
      end

      @username = username
    end

    # Custom attribute writer method with validation
    # @param [Object] new_password Value to be assigned
    def new_password=(new_password)
      if !new_password.nil? && new_password.to_s.length > 255
        fail ArgumentError, 'invalid value for "new_password", the character length must be smaller than or equal to 255.'
      end

      if !new_password.nil? && new_password.to_s.length < 0
        fail ArgumentError, 'invalid value for "new_password", the character length must be great than or equal to 0.'
      end

      pattern = Regexp.new(/[\P{Cc}]+/)
      if !new_password.nil? && new_password !~ pattern
        fail ArgumentError, "invalid value for \"new_password\", must conform to the pattern #{pattern}."
      end

      @new_password = new_password
    end

    # Custom attribute writer method with validation
    # @param [Object] confirm_password Value to be assigned
    def confirm_password=(confirm_password)
      if !confirm_password.nil? && confirm_password.to_s.length > 255
        fail ArgumentError, 'invalid value for "confirm_password", the character length must be smaller than or equal to 255.'
      end

      if !confirm_password.nil? && confirm_password.to_s.length < 0
        fail ArgumentError, 'invalid value for "confirm_password", the character length must be great than or equal to 0.'
      end

      pattern = Regexp.new(/[\P{Cc}]+/)
      if !confirm_password.nil? && confirm_password !~ pattern
        fail ArgumentError, "invalid value for \"confirm_password\", must conform to the pattern #{pattern}."
      end

      @confirm_password = confirm_password
    end

    # Custom attribute writer method with validation
    # @param [Object] fullname Value to be assigned
    def fullname=(fullname)
      if !fullname.nil? && fullname.to_s.length > 255
        fail ArgumentError, 'invalid value for "fullname", the character length must be smaller than or equal to 255.'
      end

      if !fullname.nil? && fullname.to_s.length < 0
        fail ArgumentError, 'invalid value for "fullname", the character length must be great than or equal to 0.'
      end

      pattern = Regexp.new(/[\P{Cc}]+/)
      if !fullname.nil? && fullname !~ pattern
        fail ArgumentError, "invalid value for \"fullname\", must conform to the pattern #{pattern}."
      end

      @fullname = fullname
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if !email.nil? && email.to_s.length > 255
        fail ArgumentError, 'invalid value for "email", the character length must be smaller than or equal to 255.'
      end

      if !email.nil? && email.to_s.length < 0
        fail ArgumentError, 'invalid value for "email", the character length must be great than or equal to 0.'
      end

      pattern = Regexp.new(/[\P{Cc}]+/)
      if !email.nil? && email !~ pattern
        fail ArgumentError, "invalid value for \"email\", must conform to the pattern #{pattern}."
      end

      @email = email
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          username == o.username &&
          new_password == o.new_password &&
          confirm_password == o.confirm_password &&
          last_password_change == o.last_password_change &&
          fullname == o.fullname &&
          email == o.email &&
          suspended == o.suspended &&
          force_password_change == o.force_password_change &&
          non_expiry_password == o.non_expiry_password &&
          teams == o.teams &&
          permissions == o.permissions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [username, new_password, confirm_password, last_password_change, fullname, email, suspended, force_password_change, non_expiry_password, teams, permissions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        DependencyTracker.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
