=begin
#Dependency-Track API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DependencyTacker::ApiKey
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ApiKey' do
  before do
    # run before each test
    @instance = DependencyTacker::ApiKey.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiKey' do
    it 'should create an instance of ApiKey' do
      expect(@instance).to be_instance_of(DependencyTacker::ApiKey)
    end
  end
  describe 'test attribute "key"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
