=begin
#Dependency-Track API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

# Common files
require 'dependency-tracker-client/api_client'
require 'dependency-tracker-client/api_error'
require 'dependency-tracker-client/version'
require 'dependency-tracker-client/configuration'

# Models
require 'dependency-tracker-client/models/about'
require 'dependency-tracker-client/models/analysis'
require 'dependency-tracker-client/models/analysis_comment'
require 'dependency-tracker-client/models/analysis_request'
require 'dependency-tracker-client/models/api_key'
require 'dependency-tracker-client/models/body_part'
require 'dependency-tracker-client/models/bom_submit_request'
require 'dependency-tracker-client/models/clone_project_request'
require 'dependency-tracker-client/models/component'
require 'dependency-tracker-client/models/component_metrics'
require 'dependency-tracker-client/models/config_property'
require 'dependency-tracker-client/models/content_disposition'
require 'dependency-tracker-client/models/cwe'
require 'dependency-tracker-client/models/dependency'
require 'dependency-tracker-client/models/dependency_metrics'
require 'dependency-tracker-client/models/dependency_request'
require 'dependency-tracker-client/models/finding'
require 'dependency-tracker-client/models/form_data_body_part'
require 'dependency-tracker-client/models/form_data_content_disposition'
require 'dependency-tracker-client/models/form_data_multi_part'
require 'dependency-tracker-client/models/framework'
require 'dependency-tracker-client/models/identifiable_object'
require 'dependency-tracker-client/models/ldap_user'
require 'dependency-tracker-client/models/license'
require 'dependency-tracker-client/models/managed_user'
require 'dependency-tracker-client/models/mapped_ldap_group'
require 'dependency-tracker-client/models/mapped_ldap_group_request'
require 'dependency-tracker-client/models/media_type'
require 'dependency-tracker-client/models/multi_part'
require 'dependency-tracker-client/models/notification_publisher'
require 'dependency-tracker-client/models/notification_rule'
require 'dependency-tracker-client/models/package_url'
require 'dependency-tracker-client/models/parameterized_header'
require 'dependency-tracker-client/models/permission'
require 'dependency-tracker-client/models/portfolio_metrics'
require 'dependency-tracker-client/models/project'
require 'dependency-tracker-client/models/project_metrics'
require 'dependency-tracker-client/models/project_property'
require 'dependency-tracker-client/models/repository'
require 'dependency-tracker-client/models/repository_meta_component'
require 'dependency-tracker-client/models/score'
require 'dependency-tracker-client/models/search_result'
require 'dependency-tracker-client/models/tag'
require 'dependency-tracker-client/models/team'
require 'dependency-tracker-client/models/user_principal'
require 'dependency-tracker-client/models/vulnerability'
require 'dependency-tracker-client/models/vulnerability_metrics'
require 'dependency-tracker-client/models/vulnerable_software'

# APIs
require 'dependency-tracker-client/api/analysis_api'
require 'dependency-tracker-client/api/badge_api'
require 'dependency-tracker-client/api/bom_api'
require 'dependency-tracker-client/api/calculator_api'
require 'dependency-tracker-client/api/component_api'
require 'dependency-tracker-client/api/config_property_api'
require 'dependency-tracker-client/api/cwe_api'
require 'dependency-tracker-client/api/default_api'
require 'dependency-tracker-client/api/dependency_api'
require 'dependency-tracker-client/api/finding_api'
require 'dependency-tracker-client/api/ldap_api'
require 'dependency-tracker-client/api/license_api'
require 'dependency-tracker-client/api/metrics_api'
require 'dependency-tracker-client/api/permission_api'
require 'dependency-tracker-client/api/project_api'
require 'dependency-tracker-client/api/project_property_api'
require 'dependency-tracker-client/api/repository_api'
require 'dependency-tracker-client/api/search_api'
require 'dependency-tracker-client/api/team_api'
require 'dependency-tracker-client/api/user_api'
require 'dependency-tracker-client/api/version_api'
require 'dependency-tracker-client/api/vulnerability_api'

module DependencyTracker
  class << self
    # Customize default settings for the SDK using block.
    #   DependencyTracker.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
